### ISSUE TITLE
wrong Instruction in readme

### ISSUE THREAD

**Issue by urza** [coffee-tools/folgore#80]
This instruction in readme:
`coffee --network <your network> add remote folgore-git https://github.com/coffee-tools/folgore.git`

should be
`coffee --network <your network> remote add folgore-git https://github.com/coffee-tools/folgore.git`

(swap `remote` and `add`)

**Comment by raehat** [comment]
I spent quite some time figuring out why add remote isn't working, thanks for this!

**Comment by vincenzopalazzo** [comment]
Thanks! for the catch,

Some of @tareknaser or @Harshit933 want to take this issue over?
