### ISSUE TITLE
Missing step? How to enable lightningd with coffee and folgore?

### ISSUE THREAD

**Issue by urza** [coffee-tools/folgore#81]
I am probably stupid, but I seem to be missing something.

I have CLN installed.
I also installed nakamoto and coffee and folgore following the instructions.

Nakamoto is running and synced (but just from command line, not as http server).

How do I tell my CLN to use folgore with nakamoto as bitcoin backend?

I added this to my lightning config:
`bitcoin-client=nakamoto`
and removed the regular setup to bitcoind I have there.

But when I start lightningd I get this error:
`bitcoin-client=nakamoto: unknown option`

**Comment by vincenzopalazzo** [comment]
What happens when you do `coffee --network <your network> list`?

I suspect that you skip the `coffee --network <your network> setup <path of the .lightning root>` or what happens often is that you do not specify the network

**Comment by urza** [comment]
> I suspect that you skip the `coffee --network <your network> setup <path of the .lightning root>`

Oh yes, that's it. I missed this one.

I was just doing these steps here: https://coffee-docs.netlify.app/install-coffee
but this one is on the next page in using instructions :)

**Comment by vincenzopalazzo** [comment]
You need also to read the step here https://coffee-docs.netlify.app/using-coffee


Closing this, but feel free to reopen if there is some other problem
