### ISSUE TITLE
"option name 'bitcoin-rpcuser' is already taken" error when trying to run folgore with "lightningd --testnet"

### ISSUE THREAD

**Issue by raehat** [coffee-tools/folgore#83]
I ran "lightningd --testnet" successfully yesterday with folgore. I played around with lightning testnet network, everything was fine. Today, when I tried to run "lightningd --testnet" again, this error pops up

```error starting plugin '/home/mephisto/.coffee/testnet/plugins/folgore/target/release/folgore_plugin': option name 'bitcoin-rpcuser' is already taken```

seemed like a trivial issue at first site, checked for any "bitcoin-rpcuser" option mentioned in config file causing conflicts, there wasn't any. Deleted config file, deleted core lightning repository, cloned it and rebuilt it, still issue persists. 

Any other way to debug this issue?

**Comment by vincenzopalazzo** [comment]
Right, you need to run core lightning with `--disable-plugin bcli`, so in your case `lightningd --testnet --disable-plugin bcli`

I am happy to review your PR if you add this to the readme

**Comment by raehat** [comment]
unfortunately, it doesn't solve the issue for me :(
it can be something stupid on my side too, any other way to debug this? check if I already set bitcoin rpcuser somewhere?

**Comment by raehat** [comment]
wait no, it did solve the issue, I apologize!
but now something seems to be loading forever
![image](https://github.com/coffee-tools/folgore/assets/77321971/367b3270-d077-4f52-95e8-4b7cf6e54fc9)

is this supposed to happen?
and yes I'll issue a new PR readme in a while

**Comment by vincenzopalazzo** [comment]
nakamoto is syncing with the network so it need some time to keep up

**Comment by raehat** [comment]
I thought this plugin is used to connect your local lightning node to a remote bitcoin node, so why sync happens?

**Comment by vincenzopalazzo** [comment]
>I thought this plugin is used to connect your local lightning node to a remote bitcoin node, so why sync happens?

Because `nakamoto` is not a remote node, please see https://github.com/cloudhead/nakamoto

If you want just a remote API, try `bitcoin-client=esplora`

Closing this as solved and open an issue to track the missing documentation
