### ISSUE TITLE
What needs to be in lightning config?

### ISSUE THREAD

**Issue by urza** [coffee-tools/folgore#84]
Coffee is now working, but when I start lightningd I get this error:

```
 lightningd
2024-05-15T11:45:44.292Z INFO    lightningd: v24.02.2
error starting plugin '/home/alice/.coffee/bitcoin/plugins/folgore/target/release/folgore_plugin': option name 'bitcoin-rpcpassword' is already taken
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

What exactly should be in my lightning config?

I commented all the bitcoin-* related lines and added `bitcoin-client=nakamoto`

so it looks something like this:

```
bitcoin-client=nakamoto

#bitcoin-rpcconnect=...
#bitcoin-rpcport=...
#bitcoin-rpcuser=...
#bitcoin-rpcpassword=...
#bitcoin-cli=...
```

**Comment by vincenzopalazzo** [comment]
Did you try https://github.com/coffee-tools/folgore?tab=readme-ov-file#how-to-configure ?

**Comment by vincenzopalazzo** [comment]
Ah no your problem is https://github.com/coffee-tools/folgore/issues/83

Closing as a duplicated because I think the error will be the same

**Comment by urza** [comment]
Ah this is duplicate, sorry: https://github.com/coffee-tools/folgore/issues/83

`disable-plugin=bcli` in lightning config solves this issue.

**Comment by vincenzopalazzo** [comment]
Nice :)
