### ISSUE TITLE
coffee/folgore/nakamoto eats 100% of my CPU

### ISSUE THREAD

**Issue by urza** [coffee-tools/folgore#89]
I was wondering why the system is so unresponsive so I opened htop and folgore is eating 100% of my CPU :)

I installed folgore via coffee plugin manager and uses nakamoto backend.

![image](https://github.com/coffee-tools/folgore/assets/189804/da29134c-bc70-410d-b55d-8bd69c9df1da)

Looking at metrics now and it is continuously at 100% since I installed coffee/fologre/nakamoto 5 days ago

![image](https://github.com/coffee-tools/folgore/assets/189804/9b3d632d-fb43-4e75-86ac-33f430056e82)

**Comment by urza** [comment]
I stopped both lightningd and nakamoto and it still sits at 100% CPU in the same way. Shouldn't the plugin stop with cln? Is it the coffee manager?

Going to reboot the system..

**Comment by urza** [comment]
After reboot it looks like this:

![image](https://github.com/coffee-tools/folgore/assets/189804/10325f45-c9c2-4c0e-8555-4d6a955be8b8)

So instead of 4 processes, there are 2, but again each of them is utilizing 100% CPU core.

**Comment by vincenzopalazzo** [comment]
Closing because duplicate https://github.com/coffee-tools/folgore/issues/25

looking for a solution, when you stop cln you also need to stop folgore unfortunately, I usually kill all folgore process.

I know how to solve this, but I would like to avoid to blue up the binary size
