### ISSUE TITLE
How to disable folgore when installed via coffee

### ISSUE THREAD

**Issue by urza** [coffee-tools/folgore#90]
This question is related to to https://github.com/coffee-tools/coffee/issues/277

I wanted to switch back to regular bitcoind backend but when I change only the lightningd config it has problems with it and I don't actually know how to disable or unsintall coffee, it keeps running.

Docs are focused only on installation and getting it run, but nothing about disabling or uninstalling.

**Comment by vincenzopalazzo** [comment]
Please see https://github.com/coffee-tools/coffee/issues/277#issuecomment-2123785627
